# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' flush spdlog
#'
#' @export
flush_spd_log <- function() {
    invisible(.Call('rticks_flush_spd_log', PACKAGE = 'rticks'))
}

#' init_logger
#'
#' init common R/Cpp logger
#' @export
init_spd_log <- function(config) {
    invisible(.Call('rticks_init_spd_log', PACKAGE = 'rticks', config))
}

#' spdlog
#'
#' write to spdlog/stdout
#' @export
spd_log <- function(lvl, s) {
    invisible(.Call('rticks_spd_log', PACKAGE = 'rticks', lvl, s))
}

#' bt_gamma
#'
#' will backtest gamma scalping
#' @export
bt_gamma <- function(clazz, data, params, config) {
    .Call('rticks_bt_gamma', PACKAGE = 'rticks', clazz, data, params, config)
}

