# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' bt_gamma
#'
#' will backtest gamma scalping
#' @export
bt_gamma <- function(clazz, data, params, config) {
    .Call('rticks_bt_gamma', PACKAGE = 'rticks', clazz, data, params, config)
}

